/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.museocentralcompensar.framesProyect;

import com.museocentralcompensar.entities.ChooseFileTxt;
import com.museocentralcompensar.entities.readTxtFile;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.NumberFormat;
import java.util.Arrays;
import java.util.Locale;
import java.util.Set;

/**
 *
 * @author equipo pc
 */
public class SecondFrameResumedRegister extends javax.swing.JFrame  {
    public  javax.swing.JList<String> listaRegistro;

    /**
     * Creates new form SecondFrameResumenRegistro
     */
    public SecondFrameResumedRegister() throws FileNotFoundException {
        initComponents();
        setIcon();

       //
        DefaultListModel<String> model = new DefaultListModel<>();
        listaRegistro.setModel(model);
        putElementsInList(model);




    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRegistro = new javax.swing.JList<>();
        AgregarVisitante = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();


        jButton2.setFont(new java.awt.Font("Futura Bk BT", 1, 12)); // NOI18N
        jButton2.setText("Crear registro");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaRegistro.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        listaRegistro.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1\t\tItem 2\t\tItem 3\t\tItem 4", " ", " ", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaRegistro.setName("listVisitants"); // NOI18N
        jScrollPane1.setViewportView(listaRegistro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        AgregarVisitante.setFont(new java.awt.Font("Futura Bk BT", 1, 12)); // NOI18N
        AgregarVisitante.setText("Agregar visitante");
        AgregarVisitante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                try {
                    AgregarVisitanteMouseReleased(evt);
                } catch (FileNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        AgregarVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarVisitanteActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Futura Bk BT", 1, 12)); // NOI18N
        Exit.setText("Salir");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Futura Bk BT", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\ProgrammingStudy\\Ucompensar\\Semestre II\\Algoritmos y Programación II\\Profundización\\MuseoCentralCompensar\\MuseoCentralCompensar\\Images\\bookReg50px.png")); // NOI18N
        jLabel1.setText("El registro de visitantes del día del día es:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AgregarVisitante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Exit))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarVisitante)
                    .addComponent(Exit))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");
        AgregarVisitante.getAccessibleContext().setAccessibleName("");
        Exit.getAccessibleContext().setAccessibleName("");
        jLabel1.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(564, 397));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarVisitanteActionPerformed(ActionEvent evt) {
    }


    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_ExitActionPerformed

    private void AgregarVisitanteMouseReleased(java.awt.event.MouseEvent evt) throws FileNotFoundException {
        ThirdFrameAgregarVisitanteGrupo frame = new ThirdFrameAgregarVisitanteGrupo();
        frame.setVisible(true);
        this.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void showPanel()  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondFrameResumedRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondFrameResumedRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondFrameResumedRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondFrameResumedRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SecondFrameResumedRegister().setVisible(true);
                } catch (FileNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }
    
    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage("E:\\ProgrammingStudy\\Ucompensar\\Semestre II\\Algoritmos y Programación II\\Profundización\\MuseoCentralCompensar\\MuseoCentralCompensar\\Images\\greenICon.png"));
    }

    public void putElementsInList(DefaultListModel model) throws FileNotFoundException {
        //Change listaRegistro to a list
        JList listaRegistro = new JList(model);
        model.clear();




        File selectedFile = ChooseFileTxt.getSelectedFile();
        readTxtFile read = new readTxtFile(selectedFile);
        Set<String> elementsSet = read.getFileContent();

        String elements = String.join("\n", elementsSet);



        if (selectedFile == null) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún archivo");
            FirstFrameElegirCrear.showPanel();
            this.setVisible(false);
        }





//Cada elemento está separado por un salto de linea:
        String[] elementsArraySeparatedByJumpLine = separateElements(elements);
        String[] elementsArraySeparatedBySpace = separateBySpace(elementsArraySeparatedByJumpLine);
        double payGroup = totalPay(elementsArraySeparatedBySpace);


//Poner los elementos sobrecribiendo la anterior lista
        for (int i = 0, j = 1; i < elementsArraySeparatedByJumpLine.length; i++, j++) {
            //Poner un númreo a cada elemento del array elementsArraySeparatedByJumpLine
            //Si es un salto de linea, no ponerle un número
            if (elementsArraySeparatedByJumpLine[i].equals("")) {
                //remove the element:
                j--;
                continue;
            }
            elementsArraySeparatedByJumpLine[i] = j + ". " + elementsArraySeparatedByJumpLine[i];
            model.addElement(elementsArraySeparatedByJumpLine[i]);
        }



//Put total pay in the list
        model.addElement("Total a pagar: " + imprimirTotalPay(payGroup));
        listaRegistro.setModel(model);


    }

    public double totalPay(String[] elements) {
        double totalPay = 0;
        for (int i = 0; i < elements.length; i++) {
            String[] parts = elements[i].split("\\s+");
            String priceStr = parts[parts.length - 1];
            if (priceStr.contains(".")) {
                double price = Double.parseDouble(priceStr);
                totalPay += price;
            }
        }
        System.out.println(totalPay);
        return totalPay;
    }

    public String[] separateElements(String elements) {
        String[] elementsArray = elements.split("\n");
        for (int i = 0; i < elementsArray.length; i++) {
            //System.out.println(elementsArray[i]);
        }
        return elementsArray;
    }
    private String[] separateBySpace(String[] elements) {
        String[] elementsArray2 = new String[0];
        for (int i = 0; i < elements.length; i++) {
            String[] elementsArray = elements[i].split(" ");
            for (int j = 0; j < elementsArray.length; j++) {
                elementsArray2 = Arrays.copyOf(elementsArray2, elementsArray2.length + 1);
                elementsArray2[elementsArray2.length - 1] = elementsArray[j];
            }

    }

        return elementsArray2;
    }

    public String imprimirTotalPay(double totalPay) {
        // Crear un objeto NumberFormat para formatear el número
        NumberFormat formatter = NumberFormat.getCurrencyInstance(new Locale("es", "CO"));

        // Formatear el número
        String formattedTotalPay = formatter.format(totalPay);

        // Imprimir el número formateado
        System.out.println(formattedTotalPay);
        return formattedTotalPay;
    }








    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarVisitante;
    private javax.swing.JButton Exit;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;


    // End of variables declaration//GEN-END:variables


}

