/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.museocentralcompensar.framesProyect;

import com.museocentralcompensar.entities.categoritation;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.util.Scanner;

/**
 *
 * @author equipo pc
 */
public class ThirdFrameAgregarVisitanteGrupo extends javax.swing.JFrame {

    /**
     * Creates new form ThirdFrameAgregarVisitanteGrupo
     */

    String[] categories = {"A", "B", "C", "N"};
 
    
    public ThirdFrameAgregarVisitanteGrupo() {

        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idPerson = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        categoryField = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        AgregarVisitante = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nombreTextField.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel3.setText("Nombre completo:");

        jLabel4.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel4.setText("Id (Cédula de ciudadanía)");

        idPerson.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idPerson.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        idPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPersonActionPerformed(evt);
            }
        });
        idPerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idPersonKeyReleased(evt);
            }
        });

        edad.setToolTipText("25");
        edad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edad.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel5.setText("Categoría");

        categoryField.setModel(new javax.swing.SpinnerListModel(new String[] {"A", "B", "C", "N"}));

        jLabel6.setFont(new java.awt.Font("Futura Bk BT", 0, 13)); // NOI18N
        jLabel6.setText("Edad:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(idPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                        .addGap(74, 74, 74))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        AgregarVisitante.setFont(new java.awt.Font("Futura Bk BT", 1, 12)); // NOI18N
        AgregarVisitante.setText("Agregar visitante");
        AgregarVisitante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AgregarVisitanteMouseReleased(evt);
            }
        });
        AgregarVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarVisitanteActionPerformed(evt);
            }
        });
        AgregarVisitante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AgregarVisitanteKeyReleased(evt);
            }
        });

        atras.setFont(new java.awt.Font("Futura Bk BT", 1, 12)); // NOI18N
        atras.setText("Atrás");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                atrasMouseReleased(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Futura Bk BT", 1, 12)); // NOI18N
        Exit.setText("Salir");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Futura Bk BT", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\ProgrammingStudy\\Ucompensar\\Semestre II\\Algoritmos y Programación II\\Profundización\\MuseoCentralCompensar\\MuseoCentralCompensar\\Images\\noteAgregar50px.png")); // NOI18N
        jLabel1.setText("Agrega visitante o grupo al registro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AgregarVisitante)
                                .addGap(46, 46, 46)
                                .addComponent(atras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Exit)))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarVisitante)
                    .addComponent(atras)
                    .addComponent(Exit))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(596, 353));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextFieldActionPerformed(ActionEvent evt) {
    }

    private void idPersonActionPerformed(ActionEvent evt) {
    }

    private void edadActionPerformed(ActionEvent evt) {
    }

    private void AgregarVisitanteActionPerformed(ActionEvent evt) {
    }


    private void AgregarVisitanteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarVisitanteMouseReleased
        addVisitante();



    }//GEN-LAST:event_AgregarVisitanteMouseReleased

    private void ExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseReleased
        System.exit(0);
    }//GEN-LAST:event_ExitMouseReleased

    private void atrasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseReleased
        this.setVisible(false);
        SecondFrameResumenRegistro.showPanel();
    }//GEN-LAST:event_atrasMouseReleased

    private void AgregarVisitanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgregarVisitanteKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addVisitante();
        }
    }//GEN-LAST:event_AgregarVisitanteKeyReleased

    private void idPersonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idPersonKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addVisitante();
        }
    }//GEN-LAST:event_idPersonKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void showPanel() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThirdFrameAgregarVisitanteGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThirdFrameAgregarVisitanteGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThirdFrameAgregarVisitanteGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdFrameAgregarVisitanteGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThirdFrameAgregarVisitanteGrupo().setVisible(true);
            }
        });
    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage("E:\\ProgrammingStudy\\Ucompensar\\Semestre II\\Algoritmos y Programación II\\Profundización\\MuseoCentralCompensar\\MuseoCentralCompensar\\Images\\greenICon.png"));
    }


    private void addVisitante(){
        String name = nombreTextField.getText();
        int id = Integer.parseInt(idPerson.getText());
        int age = Integer.parseInt(edad.getText());
        Object category = categoryField.getValue();

        String type = "Visitante";
        double pay = 0;
        if (age < 18 ){
            pay = categoritation.paymentCategoryAge(age);
        }
        else {
            pay = categoritation.paymentCategory(categoryField);
        }

        //JOptionPane.showMessageDialog(null, "Visitante agregado con éxito");
        nombreTextField.setText("");
        idPerson.setText("");
        edad.setText("");

        String visitante = type +"|| Nombre: "+ name + " || Identificación: " + id + " || Edad: " + age + " || Categoría:  " + category.toString();
        JOptionPane.showMessageDialog(null, visitante +" " + "Pago: " + pay);

        try {
            putInfoTxt(name, id, age, category.toString(), type, pay);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        //SecondFrameResumenRegistro.addVisitante(name, id, age, category.toString(), type);
    }

    private void putInfoTxt(String name, int id, int age, String category, String type, double pay) throws FileNotFoundException {
        PrintWriter pw = new PrintWriter(new FileOutputStream(new File("Prueba1.txt"), true)); // abrir el archivo en modo "append" para agregar nuevas líneas
        File file = new File("Prueba1.txt");

        //Print name, id, age, category, type if the file is empty:
        if (file.length() == 0) {
            pw.println(name + " " + id + " " + age + " " + category + " " + pay);
        } else { // si el archivo ya tiene contenido, agregar la nueva línea al final
            pw.println("\n" + name + " " + id + " " + age + " " + category + " " + type + " " + pay);
        }

        pw.close();
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarVisitante;
    private javax.swing.JButton Exit;
    private javax.swing.JButton atras;
    private javax.swing.JSpinner categoryField;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField idPerson;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreTextField;
    // End of variables declaration//GEN-END:variables
}
